name: Build Web App
 
on: [push]
env:
  BUCKET_NAME : "phc-dev-github-action-deploy"
  AWS_REGION : "us-west-2"
  AWS_ROLE: "arn:aws:iam::856623153676:role/github-action-deploy-dev"
# Required to get the ID Token that will be used for OIDC. Ref https://www.eliasbrange.dev/posts/secure-aws-deploys-from-github-actions-with-oidc/
permissions:
  id-token: write
  
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
          
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
     
    - name: Restore NuGet Packages
      run: nuget restore PhonebookMVC.sln
 
    - name: Build and Publish Web App
      run: msbuild PhonebookMVC.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

#aws-actions/configure-aws-credentials@v3 is a publically available github actions
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
##https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services      
      with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: itHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
          # Upload a file to AWS s3
    - name:  Copy index.html to s3
      run: |
       echo "ls root folder"
       ls
       echo "ls bin\Release\Publish folder"
       ls bin\Release\Publish
       aws s3 cp bin\Release\Publish\* s3://${{ env.BUCKET_NAME }}/test
